apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nheek-ingress
spec:
  ingressClassName: traefik
  rules:
    - host: www.nheek.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nheek-service
                port:
                  number: 30080
