apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nheek-hpa
  namespace: cloudnative-pg
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nheek-deployment
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
