apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: nheek-vpa
  namespace: cloudnative-pg
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nheek-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: nheek
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 500m
          memory: 500Mi
