name: Production - Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - none

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.REG_PASSWORD }}" | docker login ${{ secrets.REG_REGISTRY }} -u ${{ secrets.REG_USERNAME }} --password-stdin

      - name: Build and Push Docker Images
        run: |
          docker compose build
          docker compose push

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd apps
            mkdir -p nheek
            cd nheek

            curl -O -L https://raw.githubusercontent.com/nheek/nheek./main/docker-compose.yml

            docker compose pull
            docker compose up -d && curl -d "nheek deployed successfully" https://ntfy.nheek.com/${{ secrets.NTFY_TOPIC }}
